name: ctscan-cnn
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - ipywidgets
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pillow
  - scikit-learn
  - joblib
  - tqdm
  - pytorch
  - torchvision
